# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0002_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='project_link',
            field=models.URLField(),
        ),
    ]
